AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MiPipeline
      RoleArn: arn:aws:iam::107340132840:role/policy-custom-pipeline  # Reemplaza con tu ARN
      ArtifactStore:
        Type: S3
        Location: policy-custom-pipeline-s3  # Reemplaza con tu bucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: jdasaji
                Repo: timi-py-cf
                Branch: master
                OAuthToken: "{{resolve:secretsmanager:dev/py/test-file-GitHubToken}}"  # Usa Secrets Manager
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: MiProyectoDeCodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact

  MiProyectoDeCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: MiProyectoDeCodeBuild
      ServiceRole: arn:aws:iam::107340132840:role/policy-custom-pipeline  # Asegúrate de que este rol tenga permisos para CodeBuild
      Source:
        Type: CODEPIPELINE
        BuildSpec: "pipeline/buildspec.yml"  # Cambia esto si el archivo está en otro lugar
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/standard:5.0"
        Type: LINUX_CONTAINER
