version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install aws-cdk-lib
      - pip install -r requirements.txt
  build:
    commands:
      - cdk synth
      - cdk deploy --require-approval never
