version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Autenticando con ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 107340132840.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo "Configurando variables de imagen"
      - REPOSITORY_URI=107340132840.dkr.ecr.us-east-1.amazonaws.com/mi-repo-ecr
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION  # Etiqueta la imagen con el hash del commit

  build:
    commands:
      - echo "Construyendo imagen Docker"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f lambdas/lambda_handler/Dockerfile .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

      - echo "Subiendo imagen a ECR"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo "Ejecutando CDK"
      - cdk synth
      - cdk deploy --require-approval never
