version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Autenticando con ECR"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 107340132840.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo "lambda: lambda_handler"
      - REPOSITORY_URI=107340132840.dkr.ecr.us-east-1.amazonaws.com/mi-repo-ecr
      - IMAGE_TAG=$(git rev-parse --short HEAD)  # Etiqueta la imagen con el hash del commit
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f lambdas/lambda_handler/Dockerfile .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  build:
    commands:
      - cdk synth
      - cdk deploy --require-approval never
